/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EarthQuake;

public class App {

    public static void main(String[] args) {
        EarthQuakeClient client = new EarthQuakeClient();
        client.bigQuakes();
    }
}
